# Generated by Django 4.1.2 on 2022-10-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the `name` of the category.', max_length=128, verbose_name='name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_category_list', to='products.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the `name` of the product.', max_length=128, verbose_name='name')),
                ('description', models.TextField(help_text='the `description` of the product.', max_length=1000, verbose_name='description')),
                ('price', models.PositiveIntegerField(help_text='the `price` of the product.', verbose_name='price')),
                ('salesNumber', models.PositiveIntegerField(default=0, help_text='the `sales number` of the product.', verbose_name='number of sales')),
                ('stock', models.PositiveIntegerField(help_text='the `stock` of the product.', verbose_name='stock')),
                ('createAt', models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True))),
                ('category', models.ManyToManyField(to='products.categorymodel')),
                ('user', models.ForeignKey(help_text='The user who added the product', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
